### ISSUE TITLE
Zooming images does not work

### ISSUE THREAD

**Issue by tfl** [oparoz/galleryplus#10]
I think the feature "Large, zoomable previews which can be shown in fullscreen mode" option is completely useless. Once an image is loaded (and fits into the browsers window) the server never gets asked to get a better resolution of the image at the event of zooming - i.e. mouse wheel scroll. Instead the browser does a software zoom which immediately results in poor quality.

This applies to the current Owncloud as well as to the current Nextcloud 15.1.1 GP+ plugin

**Comment by oparoz** [comment]
Project is not longer active. The successor is included in [Nextcloud](https://nextcloud.com/).
