### ISSUE TITLE
No installation option in Nextcloud 10

### ISSUE THREAD

**Issue by Karlsoost** [oparoz/galleryplus#11]
## Bug report
There is no option in Nextcloud 10 app store to install Gallery+

### Steps to reproduce

Following the instructions on https://help.nextcloud.com/t/gallery-v15-1-released/1057:
1. Go to your app store app in Nextcloud
2. Disable Gallery
3. Go to the Multimedia tab
4. Enable Gallery+

There is no option for Gallery+

### Expected behaviour

There should be an option for Gallery+

### Actual behaviour

There no install option for Gallery+ in the app store (not only in Multimedia). There is only the "normal" Gallery app in v15.0.0

### Server configuration

**Operating system**:
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-042stab111.12 x86_64)

**Web server:**
Apache/2.4.23 (Ubuntu)

**Database:**
mysql

**PHP version:**
PHP 5.5.9-1ubuntu4.19

**ownCloud version:** (see ownCloud admin page or version.php)
Nextcloud 10.0.1 (stable) 

**Updated from an older ownCloud or fresh install:**
Owncloud 9

**List of activated apps:**

 
**The content of config/config.php:**

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
no

**Are you using encryption:** yes/no
no

**Are you using custom gallery.cnf config files:** yes/no
no

### Client configuration

**Browser:**
Chromium Version 53.0.2785.143 (64-bit)

**Operating system:**
Arch Linux

**Comment by oparoz** [comment]
Hello, thanks for the report. I've had no time to update Gallery+ recently, but will make it compatible in the coming weeks.

**Comment by Karlsoost** [comment]
Sounds promising. Looking forward. :)

Best regards,
Karlsoost

**Comment by Karlsoost** [comment]
Hi,

any progress on that?

Thanks,
Karlsoost

**Comment by oparoz** [comment]
Project is not longer active. The successor is included in [Nextcloud](https://nextcloud.com/).
