### ISSUE TITLE
preview:pre-generate crashes

### ISSUE THREAD

**Issue by Bodenseematze** [oparoz/galleryplus#12]
### At my installation the command line call "occ preview:pre-generate" crashes with an unhandled exception:
`occ preview:pre-generate
An unhandled exception has been thrown:
Error: Call to a member function file_get_contents() on null in /home/www/nextcloud-11.0.1/lib/private/Files/Filesystem.php:719
Stack trace:
#0 /home/www/nextcloud-11.0.1/lib/private/legacy/image.php(597): OC\Files\Filesystem::file_get_contents('/home/www/nextc...')
#1 /home/www/nextcloud-11.0.1/lib/private/Preview/MP3.php(81): OC_Image->loadFromFile('/home/www/nextc...')
#2 /home/www/nextcloud-11.0.1/lib/private/Preview/MP3.php(65): OC\Preview\MP3->getNoCoverThumbnail()
#3 /home/www/nextcloud-11.0.1/lib/private/Preview/GeneratorHelper.php(54): OC\Preview\MP3->getThumbnail('/files/Audio/Le...', 2048, 2048, false, Object(OC\Files\View))
#4 /home/www/nextcloud-11.0.1/lib/private/Preview/Generator.php(155): OC\Preview\GeneratorHelper->getThumbnail(Object(OC\Preview\MP3), Object(OC\Files\Node\File), 2048, 2048)
#5 /home/www/nextcloud-11.0.1/lib/private/Preview/Generator.php(108): OC\Preview\Generator->getMaxPreview(Object(OC\Files\SimpleFS\SimpleFolder), Object(OC\Files\Node\File), 'audio/mpeg')
#6 /home/www/nextcloud-11.0.1/lib/private/PreviewManager.php(182): OC\Preview\Generator->getPreview(Object(OC\Files\Node\File), 32, 32, true, 'fill', 'audio/mpeg')
#7 /home/www/nextcloud-11.0.1/apps/previewgenerator/lib/Command/PreGenerate.php(158): OC\PreviewManager->getPreview(Object(OC\Files\Node\File), 32, 32, true)
#8 /home/www/nextcloud-11.0.1/apps/previewgenerator/lib/Command/PreGenerate.php(148): OCA\PreviewGenerator\Command\PreGenerate->processFile(Object(OC\Files\Node\File))
#9 /home/www/nextcloud-11.0.1/apps/previewgenerator/lib/Command/PreGenerate.php(113): OCA\PreviewGenerator\Command\PreGenerate->processRow(Array)
#10 /home/www/nextcloud-11.0.1/apps/previewgenerator/lib/Command/PreGenerate.php(91): OCA\PreviewGenerator\Command\PreGenerate->startProcessing()
#11 /home/www/nextcloud-11.0.1/3rdparty/symfony/console/Command/Command.php(256): OCA\PreviewGenerator\Command\PreGenerate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/www/nextcloud-11.0.1/3rdparty/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/www/nextcloud-11.0.1/3rdparty/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OCA\PreviewGenerator\Command\PreGenerate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/www/nextcloud-11.0.1/3rdparty/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/www/nextcloud-11.0.1/lib/private/Console/Application.php(169): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /home/www/nextcloud-11.0.1/console.php(90): OC\Console\Application->run()
#17 /home/www/nextcloud-11.0.1/occ(11): `require_once('/home/www/nextc...')`

### Steps to reproduce

happens always when I call the command...

### Expected behaviour

doesn't crash :-)

### Actual behaviour

`occ preview:pre-generate` crashes, `occ preview:generate-all` works (but takes a loooong time)

### Server configuration

**Operating system**: Debian (? don't know exactly which version - it's a shared hoster)

**Web server:** Apache 2.2.22

**Database:** MariaDB

**PHP version:** 7.0.5

**ownCloud version:** Nextcloud 11.0.1

**Updated from an older ownCloud or fresh install:** Updated from Owncloud then all Nextcloud versions up to current one.

**List of activated apps:** a lot :-)
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - audioplayer: 1.4.0
  - bookmarks: 0.9.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_downloadactivity: 1.0.0
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - rainloop: 4.26.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1

 
**The content of config/config.php:**
`{
    "system": {
        "instanceid": "oc6cff25b7b5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/home\/www\/nextcloud_data\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "version": "11.0.1.2",
        "installed": true,
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "127.0.0.1:3307",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "defaultapp": "files",
        "integrity.check.disabled": true,
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 20971520,
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "disabled",
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "singleuser": false,
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "php",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}`

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using custom gallery.cnf config files:** no

#### ownCloud log (data/owncloud.log)

`{"reqId":"th82UDK0wvVZwcZrgjmg","remoteAddr":"","app":"files","message":"Backends provided no user object for ","level":3,"time":"2017-01-26 20:54:44","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"th82UDK0wvVZwcZrgjmg","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder(NULL)\\n#1 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(65): call_user_func_array(Array, Array)\\n#2 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(282): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#3 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/files_downloadactivity\\\/lib\\\/Activity\\\/Listener.php(141): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder(NULL)\\n#4 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/files_downloadactivity\\\/lib\\\/Activity\\\/Listener.php(77): OCA\\\\FilesDownloadActivity\\\\Activity\\\\Listener->getSourcePathAndOwner('\\\/home\\\/www\\\/nextc...')\\n#5 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/files_downloadactivity\\\/lib\\\/AppInfo\\\/Application.php(47): OCA\\\\FilesDownloadActivity\\\\Activity\\\\Listener->readFile('\\\/home\\\/www\\\/nextc...')\\n#6 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OCA\\\\FilesDownloadActivity\\\\AppInfo\\\\Application->listenReadFile(Array)\\n#7 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Files\\\/View.php(1243): OC_Hook::emit('OC_Filesystem', 'read', Array)\\n#8 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Files\\\/View.php(1113): OC\\\\Files\\\\View->runHooks(Array, '\\\/home\\\/www\\\/nextc...')\\n#9 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Files\\\/View.php(577): OC\\\\Files\\\\View->basicOperation('file_get_conten...', '\\\/home\\\/www\\\/nextc...', Array)\\n#10 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Files\\\/Filesystem.php(719): OC\\\\Files\\\\View->file_get_contents('\\\/home\\\/www\\\/nextc...')\\n#11 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/legacy\\\/image.php(597): OC\\\\Files\\\\Filesystem::file_get_contents('\\\/home\\\/www\\\/nextc...')\\n#12 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Preview\\\/MP3.php(81): OC_Image->loadFromFile('\\\/home\\\/www\\\/nextc...')\\n#13 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Preview\\\/MP3.php(65): OC\\\\Preview\\\\MP3->getNoCoverThumbnail()\\n#14 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Preview\\\/GeneratorHelper.php(54): OC\\\\Preview\\\\MP3->getThumbnail('\\\/files\\\/Dokument...', 2048, 2048, false, Object(OC\\\\Files\\\\View))\\n#15 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Preview\\\/Generator.php(155): OC\\\\Preview\\\\GeneratorHelper->getThumbnail(Object(OC\\\\Preview\\\\MP3), Object(OC\\\\Files\\\\Node\\\\File), 2048, 2048)\\n#16 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Preview\\\/Generator.php(108): OC\\\\Preview\\\\Generator->getMaxPreview(Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), Object(OC\\\\Files\\\\Node\\\\File), 'audio\\\/mpeg')\\n#17 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/PreviewManager.php(182): OC\\\\Preview\\\\Generator->getPreview(Object(OC\\\\Files\\\\Node\\\\File), 32, 32, true, 'fill', 'audio\\\/mpeg')\\n#18 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(167): OC\\\\PreviewManager->getPreview(Object(OC\\\\Files\\\\Node\\\\File), 32, 32, true)\\n#19 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(155): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->parseFile(Object(OC\\\\Files\\\\Node\\\\File))\\n#20 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(153): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->parseFolder(Object(OC\\\\Files\\\\Node\\\\Folder))\\n#21 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(153): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->parseFolder(Object(OC\\\\Files\\\\Node\\\\Folder))\\n#22 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(153): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->parseFolder(Object(OC\\\\Files\\\\Node\\\\Folder))\\n#23 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(153): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->parseFolder(Object(OC\\\\Files\\\\Node\\\\Folder))\\n#24 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(142): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->parseFolder(Object(OC\\\\Files\\\\Node\\\\Folder))\\n#25 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(96): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->generateUserPreviews(Object(OC\\\\User\\\\User))\\n#26 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/User\\\/Manager.php(410): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->OCA\\\\PreviewGenerator\\\\Command\\\\{closure}(Object(OC\\\\User\\\\User))\\n#27 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/apps\\\/previewgenerator\\\/lib\\\/Command\\\/Generate.php(97): OC\\\\User\\\\Manager->callForSeenUsers(Object(Closure))\\n#28 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(256): OCA\\\\PreviewGenerator\\\\Command\\\\Generate->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#29 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(818): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#30 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(186): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OCA\\\\PreviewGenerator\\\\Command\\\\Generate), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#31 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(117): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#32 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Console\\\/Application.php(169): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#33 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n#34 \\\/home\\\/www\\\/nextcloud-11.0.1\\\/occ(11): require_once('\\\/home\\\/www\\\/nextc...')\\n#35 {main}\",\"File\":\"\\\/home\\\/www\\\/nextcloud-11.0.1\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":366}","level":3,"time":"2017-01-26 20:54:44","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"th82UDK0wvVZwcZrgjmg","remoteAddr":"","app":"PHP","message":"filesize(): stat failed for \/home\/www\/nextcloud_data\/data\/Matthias\/files\/home\/www\/nextcloud-11.0.1\/core\/img\/filetypes\/audio.svg at \/home\/www\/nextcloud-11.0.1\/lib\/private\/Files\/Storage\/Local.php#211","level":3,"time":"2017-01-26 20:54:44","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"th82UDK0wvVZwcZrgjmg","remoteAddr":"","app":"PHP","message":"fopen(\/home\/www\/nextcloud_data\/data\/Matthias\/files\/home\/www\/nextcloud-11.0.1\/core\/img\/filetypes\/audio.svg): failed to open stream: No such file or directory at \/home\/www\/nextcloud-11.0.1\/lib\/private\/Files\/Storage\/Local.php#216","level":3,"time":"2017-01-26 20:54:44","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"th82UDK0wvVZwcZrgjmg","remoteAddr":"","app":"PHP","message":"fread() expects parameter 1 to be resource, boolean given at \/home\/www\/nextcloud-11.0.1\/lib\/private\/Files\/Storage\/Local.php#217","level":3,"time":"2017-01-26 20:54:44","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"th82UDK0wvVZwcZrgjmg","remoteAddr":"","app":"PHP","message":"fclose() expects parameter 1 to be resource, boolean given at \/home\/www\/nextcloud-11.0.1\/lib\/private\/Files\/Storage\/Local.php#218","level":3,"time":"2017-01-26 20:54:44","method":"--","url":"--","user":"--","version":"11.0.1.2"}
{"reqId":"th82UDK0wvVZwcZrgjmg","remoteAddr":"","app":"PHP","message":"imagecreatefromstring(): Empty string or invalid image at \/home\/www\/nextcloud-11.0.1\/lib\/private\/legacy\/image.php#597","level":3,"time":"2017-01-26 20:54:44","method":"--","url":"--","user":"--","version":"11.0.1.2"}
`

### Client configuration

**Browser:**

**Operating system:**

**Comment by Bodenseematze** [comment]
I hope this is the correct place to report this bug?
It's not in Gallery+ but I assume the integrated Gallery app in Nextcloud 11+ is actually gallery+?

**Comment by oparoz** [comment]
Hello,
This is the wrong repository :)
Looks like this bug has already been reported in the proper app repository:
https://github.com/rullzer/previewgenerator/issues/17

I'll let you subscribe to that issue.
